version: "2"
services:
  db:
    image: "mysql:5.7"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: adminuser
      MYSQL_DATABASE: BOOKSINFO
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
  assignment1-cloud:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
